return {
    -- statusline
    {
        "nvim-lualine/lualine.nvim",
        dependencies = {
            "nvim-tree/nvim-web-devicons",
        },
        opts = {
            theme = 'tokyonight',
        }
    }
}
-- return {
--     -- ayu colorscheme
--     {
--         "shatur/neovim-ayu",
--         lazy = false,    -- load immediately
--         priority = 1000, -- make sure it loads before other plugins
--         config = function()
--             require("ayu").setup({
--                 mirage = false,                   -- true for ayu mirage variant
--                 overrides = {
--                     Boolean = { fg = "#FFB454" }, -- Change to orange
--                     Number = { fg = "#FFB454" },  -- Change to orange
--                 }
--             })
--             vim.cmd("colorscheme ayu")
--             vim.o.termguicolors = true
--             vim.o.background = "dark"
--         end,
--     },

--     -- statusline
--     {
--         "nvim-lualine/lualine.nvim",
--         dependencies = {
--             "nvim-tree/nvim-web-devicons",
--         },
--         opts = {
--             theme = 'tokyonight',
--         }
--     }
--{
--    "nvim-lualine/lualine.nvim",
--    dependencies = { "nvim-tree/nvim-web-devicons" },
--    config = function()
--        require("lualine").setup({
--            options = {
--                theme = "solarized_dark", -- change to "ayu_mirage" if mirage = true
--                --                    component_separators = { left = '', right = '' },
--                --		    section_separators = { left = '', right = '' },
--            },
--        })
--    end,
--},
-- }
-- return {
--    {
--        --        "EdenEast/carbonfox.nvim",
--        "folke/tokyonight.nvim",
--        config = function()
--            vim.cmd.colorscheme("tokyonight")
--            --vim.cmd.colorscheme = "carbonfox"
--            --            enable_transparency()
--        end
--    },
--    {
--        "nvim-lualine/lualine.nvim",
--        dependencies = {
--            "nvim-tree/nvim-web-devicons",
--        },
--        opts = {
--            theme = 'tokyonight',
--        }
--    }
--}
--
--return {
--    {
--        "rebelot/kanagawa.nvim",
--        config = function()
--            vim.cmd.colorscheme("kanagawa-dragon")
--            --vim.cmd.colorscheme = "carbonfox"
--            --            enable_transparency()
--        end
--    },
--    {
--        "nvim-lualine/lualine.nvim",
--        dependencies = {
--            "nvim-tree/nvim-web-devicons",
--        },
--        opts = {
--            theme = 'tokyonight',
--        }
--    }
--}
-- return {
--     {
--         "rose-pine/neovim",
--         name = "rose-pine",
--         config = function()
--             require('rose-pine').setup({
--                 variant = 'moon',      -- auto, main, moon, or dawn
--                 dark_variant = 'moon', -- main, moon, or dawn
--                 disable_background = false,
--                 disable_float_background = false,
--                 styles = {
--                     bold = true,
--                     italic = true,
--                     transparency = false,
--                 },
--                 groups = {
--                     -- You can customize specific highlight groups here
--                     background = 'base',
--                     background_nc = '_experimental_nc',
--                     panel = 'surface',
--                     panel_nc = 'base',
--                     border = 'highlight_med',
--                     comment = 'muted',
--                     link = 'iris',
--                     punctuation = 'subtle',

--                     error = 'love',
--                     hint = 'iris',
--                     info = 'foam',
--                     warn = 'gold',

--                     headings = {
--                         h1 = 'iris',
--                         h2 = 'foam',
--                         h3 = 'rose',
--                         h4 = 'gold',
--                         h5 = 'pine',
--                         h6 = 'foam',
--                     }
--                 },
--                 highlight_groups = {
--                     -- Make the background darker
--                     Normal = { bg = '#16141f' }, -- Darker than default
--                     NormalFloat = { bg = '#16141f' },
--                     -- You can also try these alternatives:
--                     -- Normal = { bg = '#191724' }, -- Rose Pine main background
--                     -- Normal = { bg = '#232136' }, -- Rose Pine moon background
--                 }
--             })

--             vim.cmd.colorscheme("rose-pine")

--             -- Additional terminal-specific settings for darker background
--             vim.opt.termguicolors = true
--             vim.opt.background = "dark"
--         end
--     },
--     {
--         "nvim-lualine/lualine.nvim",
--         dependencies = {
--             "nvim-tree/nvim-web-devicons",
--         },
--         opts = {
--             theme = 'rose-pine', -- Changed to match your colorscheme
--         }
--     }
-- }
--
-- return {
--     {
--         "catppuccin/nvim",
--         name = "catppuccin",
--         priority = 1000,
--         config = function()
--             require("catppuccin").setup({
--                 flavour = "mocha", -- latte, frappe, macchiato, mocha
--                 background = {
--                     light = "latte",
--                     dark = "mocha",
--                 },
--                 transparent_background = false,
--                 show_end_of_buffer = false,
--                 term_colors = false,
--                 dim_inactive = {
--                     enabled = false,
--                     shade = "dark",
--                     percentage = 0.15,
--                 },
--             })
--             vim.cmd.colorscheme("catppuccin")
--         end
--     },
--     {
--         "nvim-lualine/lualine.nvim",
--         dependencies = { "nvim-tree/nvim-web-devicons" },
--         opts = { theme = 'catppuccin' }
--     }
-- }
